language: ruby
rvm:
  - 2.2.2

script:
  - bundle install
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec

addons:
  code_climate:
    repo_token: 0fe0ecadfc96d8a389f867b9ed5068b2192fe84ed78f9310c2acbfdae41a1c64 bundle exec rake
